routes/web.php
    Route::post('update-product-items', array('as' => 'update-product-items', 'uses' => 'Doctor\DoctorController@update_product_items'));
//Update Dose
    Route::post('update-product-doses', array('as' => 'update-product-doses', 'uses' => 'Doctor\DoctorController@update_product_doses'));
    //Save Order Prescription
    Route::post('save-order-prescription', array('as' => 'save-order-prescription', 'uses' => 'Doctor\DoctorController@save_order_prescription'));
    //LogOut
    Route::get('logoutdoctor', array('as' => 'logoutdoctor.doctor', 'uses' => 'LoginController@logoutdoctor'));
    //Get auto data
    Route::get('autocomplet-search-product', array('as' => 'autocomplet_search', 'uses' => 'Doctor\DoctorController@autocomplet_search'));
    //Here is info
    Route::post('add-medicine-extra', array('as' => 'add-medicine-extra', 'uses' => 'Doctor\DoctorController@add_medicine_extra'));

    Route::post('send-request-to-user', array('as' => 'send-request-to-user', 'uses' => 'Doctor\DoctorController@sendRequestToUser'));
    /*Completed Consutatino*/
   // Route::post('completedConsultation', array('as' => 'completedConsultation', 'uses' => 'Doctor\DoctorController@completedConsultation '));
    //Remove medicens here
    Route::post('remove-product-items', array('as' => 'remove-product-items', 'uses' => 'Doctor\DoctorController@remove_product_items'));
        // Doctor availability 
    Route::post('doctor-availablity', array('as' => 'doctor-availablity', 'uses' => 'Doctor\DoctorController@availablity'));
           /*Notification*/
    Route::get('notification', array('as' => 'notification', 'uses' => 'Doctor\DoctorController@notification'));
        //view all notification
    Route::post('view_all/{id}', array('as' => 'doctor.view-all', 'uses' => 'Doctor\DoctorController@view_all'));

     // Document Upload
    Route::post('document', array('as' => 'doctor.document', 'uses' => 'Doctor\DoctorController@document')); 

});


/*============================== Web Route End =============*/


/*===================================== Admin Routes Section =====================================*/
/*============= Login Route Start =============*/
Route::group(['prefix' => 'admin'], function () {
    Route::get('/', array('as' => 'admin.login', 'uses' => 'Admin\LoginController@index'));
    Route::get('login', array('as' => 'admin.login', 'uses' => 'Admin\LoginController@index'));
    Route::post('login', array('as' => 'admin.login.post', 'uses' => 'Admin\LoginController@doLogin'));
});

    Route::get('logout', array('as' => 'admin.logout.post', 'uses' => 'Admin\LoginController@logout'));

/*============= Dashboard Route Start =============*/
Route::group(['prefix'=>'/admin','middleware'=>['admin.auth']],function(){

Route::get('dashboard', array('as' => 'admin.dashboard', 'uses' => 'Admin\LoginController@dashboard'));


/*============= Profile Route Start =============*/


Route::get('profile', array('as' => 'profile', 'uses' => 'Admin\ProfileController@index'));
Route::post('change-password', array('as' => 'change.password', 'uses' => 'Admin\ProfileController@change_password'));


 //Edit
Route::get('edit/{id}', array('as' => 'user.edit', 'uses' => 'Admin\UserController@edit'));
Route::post('edit/{id}', array('as' => 'user.edit.post', 'uses' => 'Admin\UserController@update'));

/*Role ===========*/
Route::resource('roles', 'Admin\RolesController');
Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');


/*============= Category Route Start =============*/
Route::group(array('prefix' => 'category'), function () {
        //View
        Route::get('list', array('as' => 'admin.category.list', 'uses' => 'Admin\CategoryController@index'));
          //sub-category
    Route::get('sub-catgory/{id}', array('as' => 'admin.category.sub_catgory', 'uses' => 'Admin\CategoryController@sub_catgory'));

    Route::get('data/{id}', array('as' => 'admin.category.sub-category.list.data', 'uses' => 'Admin\CategoryController@data_sub_cat'));
         //Insert
        Route::get('add', array('as' => 'admin.category.add', 'uses' => 'Admin\CategoryController@create'));
        Route::post('add', array('as' => 'admin.category.add.post', 'uses' => 'Admin\CategoryController@store'));
        //Update
        Route::get('edit/{id}', array('as' => 'admin.category.edit', 'uses' => 'Admin\CategoryController@edit'));
        Route::post('edit/{id}', array('as' => 'admin.category.edit.post', 'uses' => 'Admin\CategoryController@update'));
        //Delete
       Route::get('{cat_id}/confirm-delete', array('as' => 'admin.category.delete.delete-confirm', 'uses' => 'Admin\CategoryController@getModalDelete'));
        Route::get('deletedcat/{cat_id}', array('as' => 'admin.category.delete', 'uses' => 'Admin\CategoryController@destroy'));
        //Status Update
        Route::get('update-status-confirm/{status}/{id}', array('as' => 'admin.category.updatestatus.update-status-confirm', 'uses' => 'Admin\CategoryController@status_confirm'));
            Route::get('update-status/{status}/{id}', array('as' => 'admin.category.updatestatus', 'uses' => 'Admin\CategoryController@update_status'));
});



/*============= Page Route Start =============*/
Route::group(array('prefix' => 'setting'), function () {
        //View
        Route::get('list', array('as' => 'admin.setting.list', 'uses' => 'Admin\SettingController@index'));

        Route::POST('update-general-setting', array('as' => 'admin.update.general.setting', 'uses' => 'Admin\SettingController@update_general_setting'));

        Route::POST('update-site-setting', array('as' => 'admin.update.site-setting.setting', 'uses' => 'Admin\SettingController@update_site_setting_setting'));

        Route::POST('update-payment-setting', array('as' => 'admin.update.payment-setting.setting', 'uses' => 'Admin\SettingController@update_payment_setting'));

        Route::POST('update-push-notification', array('as' => 'admin.update.push-notification.setting', 'uses' => 'Admin\SettingController@update_push_notification'));

});

/*============= Page Route Start =============*/
Route::group(array('prefix' => 'page'), function () {
        //View
        Route::get('list', array('as' => 'admin.page.list', 'uses' => 'Admin\PageController@index'));
         //Insert
        Route::get('add', array('as' => 'admin.page.add', 'uses' => 'Admin\PageController@create'));
        Route::post('add', array('as' => 'admin.page.add.post', 'uses' => 'Admin\PageController@store'));
        //Update
        Route::get('edit/{id}', array('as' => 'admin.page.edit', 'uses' => 'Admin\PageController@edit'));
        Route::post('edit/{id}', array('as' => 'admin.page.edit.post', 'uses' => 'Admin\PageController@update'));
        //Delete
       Route::get('{cat_id}/confirm-delete', array('as' => 'admin.page.delete.delete-confirm', 'uses' => 'Admin\PageController@getModalDelete'));
        Route::get('deletedcat/{cat_id}', array('as' => 'admin.page.delete', 'uses' => 'Admin\PageController@destroy'));
        //Status Update
        Route::get('update-status-confirm/{status}/{id}', array('as' => 'admin.page.updatestatus.update-status-confirm', 'uses' => 'Admin\PageController@status_confirm'));
            Route::get('update-status/{status}/{id}', array('as' => 'admin.page.updatestatus', 'uses' => 'Admin\PageController@update_status'));
});

/*============= manufacturer Route Start =============*/
Route::group(array('prefix' => 'manufacturer'), function () {
        //View
        Route::get('list', array('as' => 'admin.manufacturer.list', 'uses' => 'Admin\ManufacturerController@index'));
         //Insert
        Route::get('add', array('as' => 'admin.manufacturer.add', 'uses' => 'Admin\ManufacturerController@create'));
        Route::post('add', array('as' => 'admin.manufacturer.add.post', 'uses' => 'Admin\ManufacturerController@store'));
        //Update
        Route::get('edit/{id}', array('as' => 'admin.manufacturer.edit', 'uses' => 'Admin\ManufacturerController@edit'));
        Route::post('edit/{id}', array('as' => 'admin.manufacturer.edit.post', 'uses' => 'Admin\ManufacturerController@update'));
        //Delete
       Route::get('{cat_id}/confirm-delete', array('as' => 'admin.manufacturer.delete.delete-confirm', 'uses' => 'Admin\ManufacturerController@getModalDelete'));
        Route::get('deletedcat/{cat_id}', array('as' => 'admin.manufacturer.delete', 'uses' => 'Admin\ManufacturerController@destroy'));
        //Status Update
        Route::get('update-status-confirm/{status}/{id}', array('as' => 'admin.manufacturer.updatestatus.update-status-confirm', 'uses' => 'Admin\ManufacturerController@status_confirm'));
            Route::get('update-status/{status}/{id}', array('as' => 'admin.manufacturer.updatestatus', 'uses' => 'Admin\ManufacturerController@update_status'));
});


/*============= Banner Route Start =============*/
Route::group(array('prefix' => 'banner'), function () {
        //View
        Route::get('list', array('as' => 'admin.banner.list', 'uses' => 'Admin\BannerController@index'));
         //Insert
        Route::get('add', array('as' => 'admin.banner.add', 'uses' => 'Admin\BannerController@create'));
        Route::post('add', array('as' => 'admin.banner.add.post', 'uses' => 'Admin\BannerController@store'));
        //Update
        Route::get('edit/{id}', array('as' => 'admin.banner.edit', 'uses' => 'Admin\BannerController@edit'));
        Route::post('edit/{id}', array('as' => 'admin.banner.edit.post', 'uses' => 'Admin\BannerController@update'));
        //Delete
       Route::get('{cat_id}/confirm-delete', array('as' => 'admin.banner.delete.delete-confirm', 'uses' => 'Admin\BannerController@getModalDelete'));
        Route::get('deletedcat/{cat_id}', array('as' => 'admin.banner.delete', 'uses' => 'Admin\BannerController@destroy'));
        //Status Update

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $fillable = ['name'];


}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Http\Request;
use App\Models\RoleHasPermission;
use App\Models\RoleUser;
use App\Models\Links;
use DB;
use Route;
use Session;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all()->where('is_backend','1');
        return view('backend.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get()->pluck('name', 'name');
        return view('backend.roles.add', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // echo "<pre>"; print_r($request->all()); die();   
        DB::beginTransaction();
      try {  
        $role = Role::create($request->except('manager_permission','action_permission'));
        $managerpermission = $request->get('manager_permission');
        $mainmenupermission = [];
        //echo "<pre>"; print_r($managerpermission); die();
        foreach($managerpermission as $key=> $val){
            $mainmenupermission[] = $key; 
            foreach($val as $value){
            $mainmenupermission[] = $value; 
            }
        }
        $actionmenupermission = [];
        $actionpermission = $request->get('action_permission');
        foreach($actionpermission as $key=> $val){
            $mainmenupermission[] = $key; 
            foreach($val as $value){
            $actionmenupermission[] = $value; 
            }
        }
       // echo "<pre>"; print_r($mainmenupermission); die();
        $mainmenupermission = implode(',',$mainmenupermission);
        Role::where('id',$role->id)->update(['permissions'=>$mainmenupermission]);
         foreach($actionmenupermission as $val){
            $addactionpermission = new RoleHasPermission();
            $addactionpermission->permission_id = $val;
            $addactionpermission->role_id = $role->id;
            $addactionpermission->save();
        }
        DB::commit();
        } catch (\Exception $e) {
            Session::flash('error',$e->getMessage());
             return redirect()->route('roles.index');


        }
        Session::flash('success', 'You have been successfully create roles');
        return redirect()->route('roles.index');
        
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show(Role $role)
    {
/*        echo "<pre>"; print_r($Role);  die();
        $role->load('permissions');
        echo "<pre>"; print_r($role); die();
*/        return view('backend.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
  public function edit(Role $role)
    {   
        $permissions = Permission::get()->pluck('name', 'name');
        $actions    = RoleHasPermission::where('role_id',$role->id)->select('permission_id')->get();
        $actionarr  = [];
        foreach($actions as $key=> $val){
            $actionarr[$key] =  $val->permission_id;
        }
        return view('backend.roles.edit', compact('role','actionarr', 'permissions'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        DB::beginTransaction();
      try {  
        $managerpermission = $request->get('manager_permission');
        $mainmenupermission = [];
        foreach($managerpermission as $key=> $val){
            $mainmenupermission[] = $key; 
            foreach($val as $value){
            $mainmenupermission[] = $value; 
            }
        }

        $actionmenupermission = [];
        $actionpermission = $request->get('action_permission');
        foreach($actionpermission as $key=> $val){
            $mainmenupermission[] = $key; 
            foreach($val as $value){
            $actionmenupermission[] = $value; 
            }
        }
        $mainmenupermission = implode(',',$mainmenupermission);
        Role::where('id',$role->id)->update(['permissions'=>$mainmenupermission]);
        RoleHasPermission::where('role_id',$role->id)->delete();
         foreach($actionmenupermission as $val){
            $addactionpermission = new RoleHasPermission();
            $addactionpermission->permission_id = $val;
            $addactionpermission->role_id = $role->id;
            $addactionpermission->save();
        }
        DB::commit();
        } catch (\Exception $e) {
            Session::flash('error',$e->getMessage());
        }
        Session::flash('success', 'You have been successfully Update roles');
        return redirect()->route('roles.index');
    }
   
    /**
     * Remove Role from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        RoleHasPermission::where('role_id',$role->id)->delete();
        $role->delete();
        Session::flash('success', 'You have been successfully deleted roles');
        return redirect()->route('roles.index');
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        Role::whereIn('id', request('ids'))->delete();
        return response()->noContent();
    }

}

resources/views/backend_old/roles/add.blade.php
@extends('backend/layouts/default')
@section('title')
Role Manager::CRM
@stop
@section('header_styles')
<link href="{{ asset('assets/css/pages/form2.css') }}" rel="stylesheet"/>
<link href="{{ asset('assets/vendors/bootstrap3-wysihtml5-bower/css/bootstrap3-wysihtml5.min.css') }}" rel="stylesheet" media="screen"/>
<link href="{{ asset('assets/css/pages/editor.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/vendors/bootstrapvalidator/css/bootstrapValidator.min.css') }}" rel="stylesheet"/>
<link href="{{ asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.css') }}" rel="stylesheet" />

@stop
{{-- Content --}}

@section('content')
<section class="content-header">
   <h1>
      Role Manager
   </h1>
   <ol class="breadcrumb">
      <li>
         
         <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
         Role Manager
         
      </li>
         @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
    </div>
    @endif
      <li>Add New Role</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">
      <div class="col-lg-12">
         <div class="panel panel-primary">
            <div class="panel-heading">
               <h3 class="panel-title">
                  <i class="livicon" data-name="wrench" data-size="16" data-loop="true" data-c="#fff"
                     data-hc="white"></i>
                  Add New Role
               </h3>
            <div class="pull-right" style="margin-top: -25px;">
                    <a href="{{ url()->previous() }}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
                    </div>
            </div>
            <div class="panel-body">
             <section id="group-selection">
  <div class="row">
    <div class="col-12">
      <div class="card">
      
        <div class="card-content collapse show">
          <div class="card-body card-dashboard">
        <form action="{{ route("roles.store") }}" method="POST" enctype="multipart/form-data">
           @csrf
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">Title*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($role) ? $role->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                </p>
            </div>
            <div class="form-group {{ $errors->has('permission') ? 'has-error' : '' }}">
                <label for="permission">Permissions*
                @if($errors->has('permission'))
                    <em class="invalid-feedback">
                        {{ $errors->first('permission') }}
                    </em>
                @endif
                <p class="helper-block">
                   
                </p>
            </div>
            <style>
            #treeview-checkbox-demo > ul,li{
                list-style:none;
            }
            </style>
            <div id="treeview-checkbox-demo">
            <ul>
            @php
                $permissioinmenus = [];
            @endphp
                @foreach(App\Models\Links::getParentMenu() as $parent)

                <li>
                   <i class="fa {{$parent->icon}}"></i> &nbsp;&nbsp;<b>{{$parent->name}}</b>
                 <ul>
                @foreach(App\Models\Links::getSubMenu($parent->id) as $submenu)
                    <li class="{{ request()->is($submenu->link) ? 'active' : '' }}">
                    @php
                     @$managerPermission = explode(',',@$role->permissions);
                    @endphp
                        <input type="checkbox" name="manager_permission[{{$parent->id}}][]" value="{{$submenu->id}}" {{ (isset($role) && in_array($submenu->id,$managerPermission)) ? 'checked' : '' }}> {{$submenu->name}}
                        <ul>
                            @foreach(App\Models\Links::getActionMenu($parent->id) as $action)
                                <li class="">
                                    <input type="checkbox" name="action_permission[{{$submenu->id}}][]" value="{{$action->id}}"  {{ (isset($actionarr) && in_array($action->id,$actionarr)) ? 'checked' : '' }}> {{$action->showing_name}}
                                </li>
                            @endforeach
                        </ul>
                    </li>
                @endforeach

                 </ul>
                </li>
                @endforeach
            </ul> 
        </div>

             <div>
                <!-- <input class="btn btn-danger" type="submit" value="Save"> -->
                <button type="submit"  class="btn btn-primary " value="Save">
                        @lang('SAVE')
                        </button>
            </div>
        </form>

        </div>
        </div>
      </div>
    </div>
  </div>
</section>
            </div>
         </div>
      </div>
   </div>
   <!-- row-->
</section>
@stop
@section('footer_scripts')
<script src="{{ asset('assets/vendors/jasny-bootstrap/js/jasny-bootstrap.js') }}" type="text/javascript">
</script>
<script src="{{ asset('assets/vendors/bootstrapvalidator/js/bootstrapValidator.min.js') }}" type="text/javascript">
</script>
<script src="{{ asset('assets/vendors/intl-tel-input/js/intlTelInput.min.js') }}" type="text/javascript">
</script>
<script src="{{ asset('assets/js/pages/validation.js') }}" type="text/javascript">
</script>
<script  src="{{ asset('assets/vendors/ckeditor/js/ckeditor.js') }}"  type="text/javascript">
</script>
<script  src="{{ asset('assets/vendors/ckeditor/js/jquery.js') }}"  type="text/javascript" >
</script>
<script  src="{{ asset('assets/vendors/ckeditor/js/config.js') }}"  type="text/javascript">
</script>
<script  src="{{ asset('assets/js/pages/editor.js') }}"  type="text/javascript">
</script>
<script  src="{{ asset('assets/js/timezones.full.js') }}"  type="text/javascript">
</script>
<script src="{{asset('public/frontend/js/toastr.min.js')}}"></script>


@stop

resources/views/backend_old/roles/index.blade.php
@extends('backend.layouts.default')

{{-- Page title --}}
@section('title')
    Region Manager::CRM
    @parent
@stop

{{-- page level styles --}}
@section('header_styles')
    <link href="{{ asset('assets/css/pages/form2.css') }}" rel="stylesheet"/>
    <link href="{{ asset('assets/css/pages/form3.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}" />
    <link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
<style type="text/css">
    .badge {
    display: inline-block;
    min-width: 14px;
    padding: 9px 3px;
    font-size: 15px;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    margin: 0.5mm;
    white-space: nowrap;
    vertical-align: baseline;
    background-color: #a94442;
    border-radius: 10px;
}
</style>

<link href="{{ asset('assets/vendors/bootstrapvalidator/css/bootstrapValidator.min.css') }}" rel="stylesheet"/>
@stop

{{-- Page content --}}
@section('content')

    <section class="content-header">
        <h1>Role Manager</h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('admin.dashboard')}}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    Dashboard
                </a>
            </li>
            <li>Role Manager</li>
            <li class="active">View All Roles</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content paddingleft_right15">
        <div class="row">
                       <div class="panel panel-primary ">
                              <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left"> <i class="livicon" data-name="users" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        Role List
                    </h4>
                    <div class="pull-right">
                    <a href="{{route('roles.create')}}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-plus"></span> Add New Role</a>
                    </div>
                </div>

                             
                <div class="panel-body">
                    <table class="table table-bordered " id="table1">
                       <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Permissions</th>
                        <th>Action</th>
                    </tr>
                </thead>
                 <tbody>
                    @foreach($roles as $key => $role)
                        <tr data-entry-id="{{ $role->id }}">
                            <td>
                                {{ $role->id ?? '' }}
                            </td>
                            <td>
                                {{ $role->name ?? '' }}
                            </td>
                            <td>
                                @foreach($role->permissions()->pluck('showing_name') as $permission)
                                    <span class="badge badge-info">{{ $permission }}</span>
                                @endforeach
                            </td>
                            <td>
                                   <a class="btn btn-success" href="{{ route('roles.edit', $role->id) }}" style="margin:1px;">
                                    Edit
                                   </a>
                                   <a class="btn btn-success" href="{{ route('roles.show', $role->id) }}" style="margin:1px;">
                                    View
                                   </a>
                                <form action="{{ route('roles.destroy', $role->id) }}" method="POST" onsubmit="return confirm('Are you sure to delete this Record?');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-danger" value="Delete">
                                </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
                </div>
            </div>
        </div>    <!-- row-->
    </section>

@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}"></script>
    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
    <script>
       
    </script>
@stop